# Generated by Django 2.1.2 on 2020-01-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('comments', models.TextField(max_length=100)),
                ('date', models.DateTimeField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=30)),
                ('Faculty', models.CharField(max_length=30)),
                ('Duration', models.CharField(max_length=10)),
                ('course_content', models.FileField(upload_to='contents')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateTimeField(max_length=30)),
            ],
        ),
    ]
